### ISSUE TITLE
How to receive return  Response  synchronously

### ISSUE THREAD

**Issue by micropu** [chronoxor/NetCoreServer#138]
http server send(xxxx) _  ,How to receive return  Response  synchronously

**Comment by micropu** [comment]
TcpSession How to receive return Response synchronously

**Comment by chronoxor** [comment]
Sync methods are not good suitable for Server/Session architecture, because it starts receiving in Connect() method with TryReceive(). You can use sync Receive() methods in some handlers (OnConnected, OnDisconnected, OnReceived, OnSent, OnEmpty), but again its a hack. 

Sync methods are useful to create simple sync clients with simple steps: Connect -> Send -> Receive -> Disconnect
