### ISSUE TITLE
Connecting to WebSocket server via javascript client causes error message related to reserved bits are on

### ISSUE THREAD

**Issue by ahychu84** [chronoxor/NetCoreServer#148]
I'm experiencing something strange. I have an existing websocket application and was hoping to upgrade the server library using NetCoreServer. I have setup the websocket server using the ChatServer example but when I connect it to via javascript using the command: var ws = new WebSocket("ws://localhost:30000"); I receiving the following error which I have never seen before.
WebSocket connection to 'ws://localhost:30000/' failed: One or more reserved bits are on: reserved1 = 0, reserved2 = 1, reserved3 = 0.

Has anyone else experienced this and is it an issue with the NetCoreServer library in the way it handles WebSocket connections?

Any insight would be much appreciated. Thank you.

**Comment by FranklyBrandon** [comment]
I have encountered this error recently, after some research it seems there are lots of reasons this may occur ranging from your websocket protocol mismatching between you client and server to settings on your proxy server. 

If you're using the latest vanilla JavaScript websockets and this library, I doubt it's an internal protocol mismatch, but it still might be because you are sending the client bad data. Does the connection close with that error WITHOUT sending any data between the server and the client? I've only ever seen this occur because of a protocol error and nothing concerning the handshake/connection. I would think your websockets are connecting fine, but erroring and closing when they send/receive bad data.

I had this error occur because I wasn't thinking and in my C# code I was using the method 'SendAsync(data)' instead of 'SendTextAsync("My string").' Is your client websocket configured to accept text/binary correctly? 

By default I believe a javascript websockets only accept text data. If you mean to send binary data from your NetCoreServer you may need to configure your client websocket differently, something along the lines of:

`var socket = new WebSocket('ws://127.0.0.1:8081');`
`socket.binaryType = 'arraybuffer' or 'blob';` 

If you are using a proxy server you may need to investigate there. Does it work without the proxy?

**Comment by ahychu84** [comment]
I was testing it locally and was definitely using SendTextAsync. I spent a couple of afternoons on it and when I couldn't figure out why the error was occurring, I just went and swapped out the websocket library which now works perfectly. At some point I might revisit this library.

**Comment by findli** [comment]
it happens only when you use session.Send() SendAsync() methods

as chronoxor stated: "SendAsync() is not a way to send user data into WebSocket! It's a low level SSL send method. WebSocket needs to have prepared frame before raw send."

[https://github.com/chronoxor/NetCoreServer/issues/88#issuecomment-775259829](https://github.com/chronoxor/NetCoreServer/issues/88#issuecomment-775259829)

`[https://github.com/chronoxor/NetCoreServer/issues/88#issuecomment-775930092](https://github.com/chronoxor/NetCoreServer/issues/88#issuecomment-775930092)`
