### ISSUE TITLE
Using destructors

### ISSUE THREAD

**Issue by shersh** [chronoxor/NetCoreServer#153]
In some classes you are using destructors, for example
https://github.com/chronoxor/NetCoreServer/blob/cb854ebb4b8d1b89f9a168b30a30476d713c2555/source/NetCoreServer/TcpSession.cs#L768

But it is bad practice using it just for calling disposing methods without working with unmanaged resource, because of perfomance costs.

**Comment by BuuKid** [comment]
I checked it out and you're right.
The class is not holding on to some expensive, unmanaged resources. To be more precise, none at all. 😄
Since the author already makes use of the disposable pattern, I think the destructor is just to ensure that resources are cleaned up, if e.g. the dependent class forgets to dispose it.

>  because of perfomance costs.

I doubt that, however. 

On the whole, I would agree that those destructors can and should definitely be removed for now.

**Comment by TailyFair** [comment]
We have an application that uses this library, we have around 120 conn/sec traffic.
We notice that memory usage is quite high, could destructors impact memory usage? Maybe by delaying GC that would force objects to be promoted to upper GC generations?

**Comment by shersh** [comment]
@TailyFair exactly. 
But in your case it would be better measure performance with diagnostic service attached for investigate real problem.

**Comment by blakepell** [comment]
@TailyFair You can call `Dispose` on the `TcpSession` when you're done with it, the way the code reads to me is you can `Dispose` but if you don't the finalizer will catch it and call `Dispose` (_probably_).  The `Dispose` method here tells the garbage collector to not run the finalizer if `Dispose` was already called.  The thing with letting the Finalizer handle it is you have no clue when it's going to run.  Maybe it will run soon, maybe it won't.  I would probably just `Dispose` it myself (and then you don't have to worry about the Finalizer or it's perf impacts).

**Comment by chronoxor** [comment]
Fixed
