### ISSUE TITLE
TcpClient.Connect vs TcpClient.ConnectAsync bug.

### ISSUE THREAD

**Issue by MikePapinski** [chronoxor/NetCoreServer#157]
I spotted that when you use TcpClient.Connect to TcpServer, the client will be able to send data to server but server will be able to read & respond but the client will not be able to read the messages received from the server. On the server we have data send increasing after each message but on Client OnReceived method is not being invoked and the status of received data is always on 0.
It took me 6h to find out what was the issue on my data streams. For me it looks like a bug. From what I think the .Connect should try to establish the connection on the same thread and provide the status of the operation (failed/revoked by server/no internet / success etc...) and .ConnectAsync should work like it is working so constantly trying to connect/reconnect on separate thread.

**Comment by jmb1304** [comment]
I can confirm that this is a bug. I have been trying to use .Connect() for several days and trying to figure out why OnReceived() is not being called. I changed it to .ConnectAsync() and it works correctly.

**Comment by GengineJS** [comment]
> I spotted that when you use TcpClient.Connect to TcpServer, the client will be able to send data to server but server will be able to read & respond but the client will not be able to read the messages received from the server. On the server we have data send increasing after each message but on Client OnReceived method is not being invoked and the status of received data is always on 0. It took me 6h to find out what was the issue on my data streams. For me it looks like a bug. From what I think the .Connect should try to establish the connection on the same thread and provide the status of the operation (failed/revoked by server/no internet / success etc...) and .ConnectAsync should work like it is working so constantly trying to connect/reconnect on separate thread.

I used connectSync and encountered the same problem as you. The server uses Multicast. If there are multiple clients, OnReceive has not been called.have you found a solution?

**Comment by jmb1304** [comment]
My solution was just to use `ConnectAsync()` as a workaround. I'm not sure about a specific fix in the library though.

**Comment by MikePapinski** [comment]
Yeah, I am also using ConnectAsync/ SendAsync etc... as a workaround

**Comment by happypsyduck** [comment]
This doesn't seem to be a bug but rather intentional behavior: See the line here at the source: https://github.com/chronoxor/NetCoreServer/blob/cb854ebb4b8d1b89f9a168b30a30476d713c2555/source/NetCoreServer/TcpClient.cs#L137

`        
/// <summary>
/// Connect the client (synchronous)
/// </summary>
/// <remarks>
/// Please note that synchronous connect will not receive data automatically!
/// You should use Receive() or ReceiveAsync() method manually after successful connection.
/// </remarks>
/// <returns>'true' if the client was successfully connected, 'false' if the client failed to connect</returns>
public virtual bool Connect()
{
`

**Comment by MikePapinski** [comment]
Thank you for replay, closing this issue.
