### ISSUE TITLE
Idle state detection and handling

### ISSUE THREAD

**Issue by TailyFair** [chronoxor/NetCoreServer#98]
We currently are using [DotNetty ](https://github.com/Azure/DotNetty) for our TCP servers, but since DotNetty is barely maintained for last 2 years, we are looking for alternatives.

One of the things DotNetty has that we use is Idle connection state detection. In DotNetty using [IdleStateHandler.cs](https://github.com/Azure/DotNetty/blob/72deeb9a09627763ef82e543109a8a85a5334095/src/DotNetty.Handlers/Timeout/IdleStateHandler.cs) there is special event if connection becomes idle with 3 options: read, write and all.

How could this be achieved with NetCoreServer?

Thank you very much!

**Comment by chronoxor** [comment]
As async server/client library it doesn't offer idle thread notification, because it don't use looping thread, but utilizes threads from the pool when some work is need (sending, receiving, connecting clients). The only thing we can offer is `OnEmpty()` handler in sessions/clients which is called when there is no pending data to send. We use this handler to produce and send more data to clients in order to avoid producing bottlenecks. Hope this will works in your case too.

There are also some useful properties `BytesPending`/`BytesSending` which can be used to check how much data waits for sending in buffers.

**Comment by TailyFair** [comment]
Maybe one option would be to have timer on which callback go through each Sessions and look for idling connections?
But this would require to have timestamps of LastBytesReceived, LastBytesSent.

**Comment by TailyFair** [comment]
Thank you for feedback, I'm closing this issue and opening https://github.com/chronoxor/NetCoreServer/issues/101 to continue more concrete solution.
